name: UltimatePing
version: 1.0.0
main: fr.neiyko.ultimateping.Main
authors: [ neiyko ]
description: Plugin permettant de voir son ping
commands:
  ping:
    description: Plugin to see your ping and those of others